name: Handle UI Update (Debug)

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to update to'
        required: true
      version:
        description: 'Version number'
        required: true
      app_name:
        description: 'Application name'
        required: true

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Update Go dependency
        id: go-update
        run: |
          COMMIT_HASH="${{ github.event.inputs.commit_hash }}"
          VERSION="${{ github.event.inputs.version }}"
          APP_NAME="${{ github.event.inputs.app_name }}"
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          
          # Generate the new version string
          NEW_VERSION="v${VERSION}-${APP_NAME}-go.0.${TIMESTAMP}-${COMMIT_HASH}"
          echo "Generated version: ${NEW_VERSION}"
          
          # Export variables for tmate session
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Prepare debug environment
        run: |
          # Create debug info file
          echo "Debug Information:" > debug_info.txt
          echo "COMMIT_HASH: ${{ env.COMMIT_HASH }}" >> debug_info.txt
          echo "VERSION: ${{ env.VERSION }}" >> debug_info.txt
          echo "APP_NAME: ${{ env.APP_NAME }}" >> debug_info.txt
          echo "TIMESTAMP: ${{ env.TIMESTAMP }}" >> debug_info.txt
          echo "NEW_VERSION: ${{ env.NEW_VERSION }}" >> debug_info.txt
          echo "Go environment:" >> debug_info.txt
          go env >> debug_info.txt
          echo "Module information:" >> debug_info.txt
          go list -m all >> debug_info.txt
          
          # Create helper script
          echo '#!/bin/bash' > debug_helper.sh
          echo 'echo "Available debug variables:"' >> debug_helper.sh
          echo 'echo "COMMIT_HASH: $COMMIT_HASH"' >> debug_helper.sh
          echo 'echo "VERSION: $VERSION"' >> debug_helper.sh
          echo 'echo "APP_NAME: $APP_NAME"' >> debug_helper.sh
          echo 'echo "TIMESTAMP: $TIMESTAMP"' >> debug_helper.sh
          echo 'echo "NEW_VERSION: $NEW_VERSION"' >> debug_helper.sh
          chmod +x debug_helper.sh

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true